---
- hosts: localhost
  connection: local
  tasks:
   - name: Create storage account
     azure_rm_storageaccount:
        resource_group: 1stRG
        name: testaccounta0
        account_type: Standard_LRS
